import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { SpeedInsights } from '@vercel/speed-insights/next';

import QueryProvider from '@/components/providers/QueryProvider';
import { Toaster } from '@/components/ui/sonner';

import './globals.css';

const inter = Inter({
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <html lang="en">
        <body className={`${inter.variable} antialiased`}>
          {children}
          <Toaster position="bottom-center" />
        </body>
        <SpeedInsights />
      </html>
    </QueryProvider>
  );
}
